
version: "3.7"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: LernDeutch123
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql/data


volumes:
  mssql_data:
    driver: local