
version: "3.7"

services:
  lern-deutsch-backend:
    build: .
    restart: always
    image: lern-deutsch-backend:latest
    container_name: lern-deutsch
    depends_on:
     - sqlserver
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    network_mode: host
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: LernDeutch123
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql/data


volumes:
  mssql_data:
    driver: local